/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package daw.prog10_tarea;

/**
 *
 * @author Víctor Luis Cerrato Segovia | DAW - @vanza 2022-2023
 */
public class panelOpcion2 extends javax.swing.JPanel {

    /**
     * Creates new form panelOpcion2
     */
    public panelOpcion2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marcaLabel = new javax.swing.JLabel();
        marcaField = new javax.swing.JTextField();
        matriculaLabel = new javax.swing.JLabel();
        matriculaField = new javax.swing.JTextField();
        kilometrosField = new javax.swing.JTextField();
        kilometrosLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        fechaField = new javax.swing.JTextField();
        descField = new javax.swing.JTextField();
        descLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        precioField = new javax.swing.JTextField();
        propietarioField = new javax.swing.JTextField();
        propietarioLabel = new javax.swing.JLabel();
        dniField = new javax.swing.JTextField();
        dniLabel = new javax.swing.JLabel();

        marcaLabel.setText("Marca");

        matriculaLabel.setText("Matricula");

        kilometrosLabel.setText("Num Km");

        fechaLabel.setText("Fecha Matriculacion");

        descLabel.setText("Descripcion");

        precioLabel.setText("Precio");

        propietarioLabel.setText("Propietario");

        dniLabel.setText("DNI Propietario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(marcaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(marcaField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(matriculaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(matriculaField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kilometrosLabel)
                        .addGap(18, 18, 18)
                        .addComponent(kilometrosField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fechaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(fechaField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descLabel)
                        .addGap(18, 18, 18)
                        .addComponent(descField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(precioLabel)
                        .addGap(18, 18, 18)
                        .addComponent(precioField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(propietarioLabel)
                        .addGap(18, 18, 18)
                        .addComponent(propietarioField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dniLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dniField)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaLabel)
                    .addComponent(marcaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matriculaLabel)
                    .addComponent(matriculaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kilometrosLabel)
                    .addComponent(kilometrosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel)
                    .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descLabel)
                    .addComponent(descField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioLabel)
                    .addComponent(precioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propietarioLabel)
                    .addComponent(propietarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLabel)
                    .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descField;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextField dniField;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField fechaField;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JTextField kilometrosField;
    private javax.swing.JLabel kilometrosLabel;
    private javax.swing.JTextField marcaField;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JTextField matriculaField;
    private javax.swing.JLabel matriculaLabel;
    private javax.swing.JTextField precioField;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JTextField propietarioField;
    private javax.swing.JLabel propietarioLabel;
    // End of variables declaration//GEN-END:variables
}
