/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package daw.prog10_tarea;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Víctor Luis Cerrato Segovia | DAW - @vanza 2022-2023
 */
public class Ventana_principal extends javax.swing.JFrame {
    
    private List<Cliente> clientes;
    private List<Vehiculo> vehiculos;
    private panelOpcion1 panelOp1;
    private panelOpcion2 panelOp2;
    private panelOpcion3 panelOp3;
    private panelOpcion4 panelOp4;

    /**
     * Creates new form Ventana_principal
     */
    public Ventana_principal() {
        this.clientes = new ArrayList<>();
        this.vehiculos = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        barraMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opCrearCliente = new javax.swing.JMenuItem();
        opCrearVehiculo = new javax.swing.JMenuItem();
        opVehiculosPorCliente = new javax.swing.JMenuItem();
        opListarTodo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        jMenu1.setText("Acciones disponibles");

        opCrearCliente.setText("Crear cliente");
        opCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCrearClienteActionPerformed(evt);
            }
        });
        jMenu1.add(opCrearCliente);

        opCrearVehiculo.setText("Crear vehiculo");
        opCrearVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCrearVehiculoActionPerformed(evt);
            }
        });
        jMenu1.add(opCrearVehiculo);

        opVehiculosPorCliente.setText("Listar vehiculos de cliente");
        opVehiculosPorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opVehiculosPorClienteActionPerformed(evt);
            }
        });
        jMenu1.add(opVehiculosPorCliente);

        opListarTodo.setText("Listar todo");
        opListarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opListarTodoActionPerformed(evt);
            }
        });
        jMenu1.add(opListarTodo);

        barraMenu.add(jMenu1);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCrearClienteActionPerformed
        // TODO add your handling code here:
        this.panelCentral = new panelOpcion1();
        //getContentPane().removeAll();
        getContentPane().add(panelCentral);
        this.panelCentral.setVisible(true);
        revalidate();
        repaint();
    }//GEN-LAST:event_opCrearClienteActionPerformed

    private void opCrearVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCrearVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opCrearVehiculoActionPerformed

    private void opVehiculosPorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opVehiculosPorClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opVehiculosPorClienteActionPerformed

    private void opListarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opListarTodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opListarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem opCrearCliente;
    private javax.swing.JMenuItem opCrearVehiculo;
    private javax.swing.JMenuItem opListarTodo;
    private javax.swing.JMenuItem opVehiculosPorCliente;
    private javax.swing.JPanel panelCentral;
    // End of variables declaration//GEN-END:variables
}
