package View;

/**
 *
 * @author Víctor
 */

import Controller.Controlador;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Model.Victoria;

public class VentanaPrograma extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrograma
     */
    
    DefaultTableModel modelo;
    private ActionListener listener;
    public VentanaPrograma() {
        initComponents();
        
        modelo = new DefaultTableModel();
        configurarTabla();
        tablaVictoria.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        etiquetaID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        etiquetaCircuito = new javax.swing.JLabel();
        tfCircuito = new javax.swing.JTextField();
        etiquetaGP = new javax.swing.JLabel();
        tfGP = new javax.swing.JTextField();
        etiquetaEquipo = new javax.swing.JLabel();
        tfEquipo = new javax.swing.JTextField();
        etiquetaAnio = new javax.swing.JLabel();
        tfAnio = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        etiquetaBuscar = new javax.swing.JLabel();
        tfBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVictoria = new javax.swing.JTable();
        btnBuscarCircuito = new javax.swing.JButton();
        btnBuscarGP = new javax.swing.JButton();
        btnBuscarEquipo = new javax.swing.JButton();
        etiquetaBuscar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Víctor Cerrato | viclucese@gmail.com | Mayo 2024 | IES ÁGORA");
        setBackground(new java.awt.Color(0, 102, 94));

        jPanel1.setBackground(new java.awt.Color(34, 153, 113));

        TITULO.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        TITULO.setForeground(new java.awt.Color(206, 220, 0));
        TITULO.setLabelFor(TITULO);
        TITULO.setText("Victorias de Fernando Alonso en F1");

        etiquetaID.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        etiquetaID.setText("ID");

        etiquetaCircuito.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        etiquetaCircuito.setText("Circuito");

        etiquetaGP.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        etiquetaGP.setText("Gran Premio");

        etiquetaEquipo.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        etiquetaEquipo.setText("Equipo");

        etiquetaAnio.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        etiquetaAnio.setText("Año");

        btnInsertar.setBackground(new java.awt.Color(102, 204, 255));
        btnInsertar.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        btnInsertar.setText("INSERTAR");

        btnActualizar.setBackground(new java.awt.Color(204, 204, 0));
        btnActualizar.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        btnEliminar.setText("ELIMINAR");

        etiquetaBuscar.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        etiquetaBuscar.setText("Texto a buscar:");

        tablaVictoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tablaVictoria);

        btnBuscarCircuito.setBackground(new java.awt.Color(204, 255, 204));
        btnBuscarCircuito.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        btnBuscarCircuito.setText("Circuito");

        btnBuscarGP.setBackground(new java.awt.Color(204, 255, 204));
        btnBuscarGP.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        btnBuscarGP.setText("Gran Premio");

        btnBuscarEquipo.setBackground(new java.awt.Color(204, 255, 204));
        btnBuscarEquipo.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        btnBuscarEquipo.setText("Equipo");

        etiquetaBuscar1.setFont(new java.awt.Font("Orbitron", 0, 12)); // NOI18N
        etiquetaBuscar1.setText("BUSCAR POR:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaCircuito)
                                    .addComponent(etiquetaID))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfCircuito, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(etiquetaGP)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(etiquetaEquipo)
                                        .addGap(49, 49, 49)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfGP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(etiquetaAnio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addComponent(TITULO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaBuscar)
                            .addComponent(etiquetaBuscar1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscarCircuito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarGP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarEquipo))
                            .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaBuscar)
                    .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCircuito)
                    .addComponent(btnBuscarGP)
                    .addComponent(btnBuscarEquipo)
                    .addComponent(etiquetaBuscar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaID)
                            .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaCircuito)
                            .addComponent(tfCircuito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaGP)
                            .addComponent(tfGP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaEquipo)
                            .addComponent(tfEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaAnio)
                            .addComponent(tfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsertar)
                            .addComponent(btnActualizar)
                            .addComponent(btnEliminar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrograma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TITULO;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarCircuito;
    private javax.swing.JButton btnBuscarEquipo;
    private javax.swing.JButton btnBuscarGP;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel etiquetaAnio;
    private javax.swing.JLabel etiquetaBuscar;
    private javax.swing.JLabel etiquetaBuscar1;
    private javax.swing.JLabel etiquetaCircuito;
    private javax.swing.JLabel etiquetaEquipo;
    private javax.swing.JLabel etiquetaGP;
    private javax.swing.JLabel etiquetaID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVictoria;
    private javax.swing.JTextField tfAnio;
    private javax.swing.JTextField tfBuscar;
    private javax.swing.JTextField tfCircuito;
    private javax.swing.JTextField tfEquipo;
    private javax.swing.JTextField tfGP;
    private javax.swing.JTextField tfID;
    // End of variables declaration//GEN-END:variables

            
    private void configurarTabla(){
        modelo.addColumn("ID");
        modelo.addColumn("Circuito");
        modelo.addColumn("Gran Premio");
        modelo.addColumn("Equipo");
        modelo.addColumn("Año");
    }
    
    public void setActionListener(Controlador listener){
        btnInsertar.addActionListener(listener);
        btnActualizar.addActionListener(listener);
        btnEliminar.addActionListener(listener);
        btnBuscarCircuito.addActionListener(listener);
        btnBuscarEquipo.addActionListener(listener);
        btnBuscarGP.addActionListener(listener);
        
        setMouseListener();
    }
    
    public void cargarDatosTabla(ArrayList<Victoria> listaVictorias){
        for (Victoria v : listaVictorias){
            Object[] fila = new Object[]{v.getId(),v.getCircuito(),v.getGp(),v.getEquipo(),v.getAnio()};
            modelo.addRow(fila);
        }
    }
    
    public void limpiarDatosTabla(){
        modelo.setRowCount(0);
    }
    
    public Victoria obtenerVictoria(){
        String idTexto = tfID.getText();
        String circuito = tfCircuito.getText();
        String gp = tfGP.getText();
        String equipo = tfEquipo.getText();
        String anioTexto = tfAnio.getText();
        int id = 0;
        int anio = 0;
        if (!idTexto.isEmpty()){
            id = Integer.parseInt(idTexto);
        }
        if (!anioTexto.isEmpty()){
            anio = Integer.parseInt(anioTexto);
        }
        return new Victoria(id, circuito, gp, equipo, anio);
    }
    
    public String obtenerTextoBuscar() {
        return tfBuscar.getText();
    }

    private void setMouseListener() {
        tablaVictoria.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                int filaSeleccionada = tablaVictoria.rowAtPoint(e.getPoint());
                
                if(e.getButton() == MouseEvent.BUTTON1 && filaSeleccionada != -1) {
                    tfID.setText(tablaVictoria.getValueAt(tablaVictoria.getSelectedRow(),0).toString());
                    tfCircuito.setText(tablaVictoria.getValueAt(tablaVictoria.getSelectedRow(),1).toString());
                    tfGP.setText(tablaVictoria.getValueAt(tablaVictoria.getSelectedRow(),2).toString());
                    tfEquipo.setText(tablaVictoria.getValueAt(tablaVictoria.getSelectedRow(),3).toString());
                    tfAnio.setText(tablaVictoria.getValueAt(tablaVictoria.getSelectedRow(),4).toString());
                }
            }
        });
    }
}
